import type { CharacterId, QuestionTopic } from './types.ts';

export interface CharacterDef {
  id: CharacterId;
  name: string;
  title: string;
  description: string;
  topics: QuestionTopic[];
  abilities: string[];
  deployCost: { energy: number; mana: number };
  power: number;
  health: number;
  /** Seconds between deployments. */
  cooldown: number;
  /** Max deployments per match (null = unlimited). */
  maxPerMatch: number | null;
  /** Trial: number of questions and required correct answers to unlock. */
  trial: { questions: number; passMark: number; level: 6 | 7 | 8 | 'advanced' };
  /** Unlocked for every new player. */
  starter: boolean;
  tier: 'core' | 'advanced' | 'dragon';
  color: string;
}

export const CHARACTERS: Record<CharacterId, CharacterDef> = {
  scout: {
    id: 'scout',
    name: 'Kidus the Scout',
    title: 'Eyes of the City',
    description: 'A swift runner from the lakeside districts who spots danger before anyone else.',
    topics: ['integers', 'arithmetic'],
    abilities: ['Reveals traps', 'Reveals selected enemy defenses', 'Low deployment cost', 'Fast movement'],
    deployCost: { energy: 15, mana: 0 },
    power: 30,
    health: 60,
    cooldown: 12,
    maxPerMatch: null,
    trial: { questions: 4, passMark: 3, level: 6 },
    starter: true,
    tier: 'core',
    color: '#38bdf8',
  },
  archer: {
    id: 'archer',
    name: 'Saba the Archer',
    title: 'Guardian of the Bridges',
    description: 'Her arrows split any target into perfect proportions.',
    topics: ['fractions', 'ratios', 'percentages'],
    abilities: ['Long-range attack', 'Effective against exposed structures', 'Can target support units'],
    deployCost: { energy: 25, mana: 5 },
    power: 55,
    health: 70,
    cooldown: 15,
    maxPerMatch: null,
    trial: { questions: 5, passMark: 4, level: 6 },
    starter: true,
    tier: 'core',
    color: '#4ade80',
  },
  guardian: {
    id: 'guardian',
    name: 'Bekele the Guardian',
    title: 'The Balanced Shield',
    description: 'Keeps every equation, and every wall, perfectly balanced.',
    topics: ['equations', 'inequalities'],
    abilities: ['Creates a temporary shield', 'Protects nearby units', 'Reduces incoming damage'],
    deployCost: { energy: 30, mana: 10 },
    power: 25,
    health: 140,
    cooldown: 20,
    maxPerMatch: null,
    trial: { questions: 5, passMark: 4, level: 7 },
    starter: false,
    tier: 'core',
    color: '#fbbf24',
  },
  giant: {
    id: 'giant',
    name: 'Tana the Giant',
    title: 'Mover of Mountains',
    description: 'Measures the world in strides and knocks down anything mis-measured.',
    topics: ['geometry', 'area', 'perimeter', 'measurement'],
    abilities: ['Damages walls', 'Strong against defensive structures', 'Expensive', 'Slow', 'High health'],
    deployCost: { energy: 50, mana: 15 },
    power: 90,
    health: 220,
    cooldown: 30,
    maxPerMatch: null,
    trial: { questions: 5, passMark: 4, level: 7 },
    starter: false,
    tier: 'core',
    color: '#fb923c',
  },
  engineer: {
    id: 'engineer',
    name: 'Meron the Engineer',
    title: 'Architect of Routes',
    description: 'Reads the city grid like a map and rebuilds it overnight.',
    topics: ['coordinates', 'scale'],
    abilities: ['Repairs structures', 'Disables traps', 'Opens alternate routes', 'Improves bridge and wall efficiency'],
    deployCost: { energy: 30, mana: 10 },
    power: 20,
    health: 90,
    cooldown: 20,
    maxPerMatch: null,
    trial: { questions: 5, passMark: 4, level: 7 },
    starter: false,
    tier: 'core',
    color: '#a78bfa',
  },
  healer: {
    id: 'healer',
    name: 'Hana the Healer',
    title: 'Keeper of the Mean',
    description: 'Finds the middle of any storm and steadies the whole team.',
    topics: ['statistics', 'probability'],
    abilities: ['Restores friendly units', 'Restores part of a structure', 'Cannot create major attack damage'],
    deployCost: { energy: 25, mana: 15 },
    power: 10,
    health: 80,
    cooldown: 18,
    maxPerMatch: null,
    trial: { questions: 5, passMark: 4, level: 8 },
    starter: false,
    tier: 'core',
    color: '#f472b6',
  },
  necromancer: {
    id: 'necromancer',
    name: 'Zena the Necromancer',
    title: 'Reader of Patterns',
    description: 'Sees the sequence hidden in every ending, and continues it.',
    topics: ['patterns', 'sequences', 'multi_step'],
    abilities: ['Revives one defeated unit', 'Limited use', 'High energy cost', 'Cannot endlessly revive units'],
    deployCost: { energy: 45, mana: 30 },
    power: 35,
    health: 75,
    cooldown: 45,
    maxPerMatch: 2,
    trial: { questions: 5, passMark: 4, level: 8 },
    starter: false,
    tier: 'advanced',
    color: '#c084fc',
  },
  dragon_standard: {
    id: 'dragon_standard',
    name: 'Abay Dragon',
    title: 'Spirit of the Blue Nile',
    description: 'Rises from the falls when a team has mastered the river of Grade 8 mathematics.',
    topics: ['equations', 'geometry', 'ratios', 'coordinates', 'probability'],
    abilities: ['Powerful area attack', 'One deployment per match', 'Long cooldown', 'High energy cost', 'Can be countered'],
    deployCost: { energy: 80, mana: 50 },
    power: 200,
    health: 300,
    cooldown: 120,
    maxPerMatch: 1,
    trial: { questions: 5, passMark: 4, level: 8 },
    starter: false,
    tier: 'dragon',
    color: '#22d3ee',
  },
  dragon_elite: {
    id: 'dragon_elite',
    name: 'Tisisat Dragon',
    title: 'The Smoking Fire',
    description: 'Forged in advanced algebra; only deep understanding can call it down.',
    topics: ['simultaneous_equations', 'functions', 'quadratics', 'trigonometry', 'coordinates'],
    abilities: [
      'Stronger strategic attack',
      'Requires multiple advanced answers',
      'Extremely high resource cost',
      'One deployment per match',
      'Does not guarantee victory',
      'Can be weakened by defender answers',
    ],
    deployCost: { energy: 120, mana: 80 },
    power: 320,
    health: 400,
    cooldown: 180,
    maxPerMatch: 1,
    trial: { questions: 5, passMark: 4, level: 'advanced' },
    starter: false,
    tier: 'dragon',
    color: '#818cf8',
  },
  dragon_mythic: {
    id: 'dragon_mythic',
    name: 'Lalibela Dragon',
    title: 'The Carved Legend',
    description: 'A once-per-season legend for those who master every path at once.',
    topics: ['multi_step', 'quadratics', 'trigonometry', 'differentiation', 'functions'],
    abilities: [
      'Rare strategic ultimate',
      'Requires mastery across several knowledge paths',
      'Very limited use',
      'Must remain balanced',
      'Must never make lower characters useless',
    ],
    deployCost: { energy: 150, mana: 120 },
    power: 420,
    health: 500,
    cooldown: 300,
    maxPerMatch: 1,
    trial: { questions: 6, passMark: 5, level: 'advanced' },
    starter: false,
    tier: 'dragon',
    color: '#f59e0b',
  },
};

export const CHARACTER_IDS = Object.keys(CHARACTERS) as CharacterId[];
